# monitoring/grafana/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: grafana
type: Opaque
stringData:
  # Change these before committing
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: changeme-please
  GF_SECURITY_SECRET_KEY: super-secret-signing-key
  POSTGRES_PASSWORD: grafana-db-pass
  POSTGRES_USER: grafana
  POSTGRES_DB: grafana
